# Generated by Django 4.2.13 on 2024-06-18 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prj_name', models.CharField(max_length=50)),
                ('prj_description', models.CharField(max_length=255)),
                ('prj_date', models.DateField(auto_now_add=True)),
                ('prj_last_modified', models.DateField(auto_now=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_p_articles', models.IntegerField()),
                ('rep_p_conferences', models.IntegerField()),
                ('rep_p_papers', models.IntegerField()),
                ('rep_p_books', models.IntegerField()),
                ('rep_p_others', models.IntegerField()),
                ('rep_n_articles_files', models.IntegerField()),
                ('rep_n_processed', models.IntegerField()),
                ('rep_n_duplicate', models.IntegerField()),
                ('rep_n_files', models.IntegerField()),
                ('rep_duration_seg', models.IntegerField()),
                ('rep_size_file', models.IntegerField()),
                ('rep_name_file_merged', models.CharField(max_length=100)),
                ('rep_date', models.DateField(auto_now_add=True)),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Project.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('id_project_files', models.AutoField(primary_key=True, serialize=False)),
                ('pf_name_file', models.CharField(max_length=100)),
                ('pf_p_articles', models.IntegerField()),
                ('pf_p_conferences', models.IntegerField()),
                ('pf_p_papers', models.IntegerField()),
                ('pf_p_books', models.IntegerField()),
                ('pf_p_others', models.IntegerField()),
                ('pf_n_entries_file', models.IntegerField()),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.project')),
            ],
        ),
    ]
