# Generated by Django 4.2.13 on 2024-07-06 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_file', models.CharField(max_length=100)),
                ('articles', models.IntegerField()),
                ('conferences', models.IntegerField()),
                ('papers', models.IntegerField()),
                ('books', models.IntegerField()),
                ('others', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Project.base')),
                ('pf_n_entries_file', models.IntegerField()),
            ],
            bases=('Project.base',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prj_name', models.CharField(max_length=50)),
                ('prj_description', models.TextField(blank=True, default='Sin descripción', null=True)),
                ('prj_date', models.DateField(auto_now_add=True)),
                ('prj_last_modified', models.DateField(auto_now=True)),
                ('prj_autosave', models.BooleanField(default=False)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Project.base')),
                ('rep_n_articles_files', models.IntegerField()),
                ('rep_n_processed', models.IntegerField()),
                ('rep_n_duplicate', models.IntegerField()),
                ('rep_n_files', models.IntegerField()),
                ('rep_duration_seg', models.IntegerField()),
                ('rep_size_file', models.IntegerField()),
                ('rep_date', models.DateField(auto_now_add=True)),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Project.project')),
            ],
            bases=('Project.base',),
        ),
        migrations.CreateModel(
            name='ProjectFilesEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfe_title', models.CharField(max_length=255)),
                ('pfe_authors', models.TextField()),
                ('pfe_year', models.IntegerField()),
                ('pfe_keywords', models.TextField()),
                ('pfe_journal', models.CharField(max_length=255)),
                ('pfe_volume', models.IntegerField()),
                ('pfe_number', models.IntegerField()),
                ('pfe_pages', models.IntegerField()),
                ('pfe_doi', models.CharField(max_length=100)),
                ('id_project_files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='Project.projectfiles')),
            ],
        ),
        migrations.AddField(
            model_name='projectfiles',
            name='id_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Project.project'),
        ),
    ]
