# Generated by Django 4.2.13 on 2024-07-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfiles',
            name='pf_search_criteria',
            field=models.TextField(blank=True, null=True),
        ),
    ]
