# Generated by Django 4.2.13 on 2024-07-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_projectfiles_pf_search_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='articles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='base',
            name='books',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='base',
            name='conferences',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='base',
            name='others',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='base',
            name='papers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='prj_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='projectfiles',
            name='pf_n_entries_file',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectfilesentries',
            name='pfe_authors',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='projectfilesentries',
            name='pfe_keywords',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='projectfilesentries',
            name='pfe_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectfilesentries',
            name='pfe_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectfilesentries',
            name='pfe_volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectfilesentries',
            name='pfe_year',
            field=models.IntegerField(default=0),
        ),
    ]
