# Generated by Django 4.2.13 on 2024-06-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_project_prj_autosave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='prj_description',
            field=models.TextField(blank=True, default='Sin descripción', null=True),
        ),
    ]
