# Generated by Django 4.2.13 on 2024-07-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_alter_projectfilesentries_pfe_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfilesentries',
            name='pfe_authors',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='projectfilesentries',
            name='pfe_keywords',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='projectfilesentries',
            name='pfe_title',
            field=models.TextField(default=''),
        ),
    ]
