# Generated by Django 4.2.13 on 2024-06-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_user_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='users/default.jpg', upload_to='profile_pics/'),
        ),
    ]
